[[redirects]]
  from = "/v1/"
  to = "/.netlify/functions/lookup"
  status = 200

[[redirects]]
  from = "/"
  to = "/v1/"
  status = 302

# Include all files in all functions
[functions]
  included_files = ["*.mmdb"]
